# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1
loader_version=0.19.2
# Mod Properties
mod_version=1.1+26.1
maven_group=com.thegameratort.titlefixer
archives_base_name=titlefixer
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.149.1+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
